//Types for ERROR ACTIONS
export const GET_ERRORS = "GET_ERRORS";

//Types for STUDENT ACTIONS
export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENT = "GET_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const GET_AGENTUR_BYSTUDENTID = "GET_AGENTUR_BYSTUDENTID";

//Types for AGENTUR ACTIONS
export const GET_AGENTURS = "GET_AGENTURS";
export const GET_AGENTUR = "GET_AGENTUR";
export const DELETE_AGENTUR = "DELETE_AGENTUR";

//Types for LEKTION ACTIONS
export const GET_LEKTIONS = "GET_LEKTIONS";
export const GET_LEKTION = "GET_LEKTION";
export const DELETE_LEKTION = "DELETE_LEKTION";

//Types for RECHNUNG ACTIONS
export const GET_RECHNUNGS = "GET_RECHNUNGS";
export const GET_RECHNUNG = "GET_RECHNUNG";
export const DELETE_RECHNUNG = "DELETE_RECHNUNG";

//Types for ZAHLUNGS ACTIONS
export const GET_ZAHLUNGS = "GET_ZAHLUNGS";
export const GET_ZAHLUNG = "GET_ZAHLUNG";
export const DELETE_ZAHLUNG = "DELETE_ZAHLUNG";
export const GET_ZAHLUNGS_BYSTUDENTID = "GET_ZAHLUNGS_BYSTUDENTID";
export const GET_ZAHLUNGS_BYSTUDENTIDANDAGENTUR =
  "GET_ZAHLUNGS_BYSTUDENTIDANDAGENTUR";

//Types for LOGOUT ACTIONS
export const GET_LOGOUT = "GET_LOGOUT";
export const GET_USER = "GET_USER";
